---
title: "02 Phylogenetic Signal"
author: "Katie Heineman"
date: "6/7/2019"
output: html_document
---

```{r setup, include=FALSE}
# Ana's seed database
seedDat <- fread("Data/Savanna seed database.csv")
setnames(seedDat,c("Vegetation type", "Dispersal mode","Moisture content", "Seed mass (mg)"), c("VegType", "DM","MC","SM" ))
seedDat[,Dormancy2Cat:=ifelse(Dormancy=="ND","ND","D")]

## Read in Trees 
# Scenario 3:  adding genera or species to their families or genera using the same approach implemented in Phylomatic and BLADJ 
phy_coll3 <- read.tree("Data/phy_coll3.tre")
# Scenario 1:  adding genera or species as basal polytomies within their families or genera 
phy_coll1 <- read.tree("Data/phy_coll1.tre")
# Scenario 2: adding genera or species randomly within their families or genera 
phy_coll2 <- read.tree("Data/phy_coll2.tre")

```

## Data Prep for Phylogenetic Analysis
```{r data prep phylo}
# Prep seed dat by making species with underscore
seedDat[,Species:=gsub(" ","_",Species)]

# Calculating Species Means
seedDat_spp <- seedDat[,.(T50_mean=mean(T50,na.rm=T),log_T50_mean=mean(log(T50),na.rm=T),GP = mean(GP,na.rm=T), sqrt_GP = mean(sqrt(GP),na.rm=T),Seedmass = mean(SM,na.rm=T), Moisture = mean(MC,na.rm=T)), by="Species"]
# The number of sucess is the averager germ percentage X 10 seeds per replicate X 10 reps
seedDat_spp[,Successes:=GP]
seedDat_spp[,Failures:=100-Successes]

seedDat_spp1 <- copy(seedDat_spp)
# Make this dataset into a matrix
rowlab <- seedDat_spp1$Species
trait_matrix = as.matrix(seedDat_spp1[,Species:=NULL])
rownames(trait_matrix) = rowlab

```

## Calculating Phylogenetic Signal Using Picante Package

The statistic calculated here is the K statistic with a one tailed test for significance relative to random type reshuffling (https://cran.r-project.org/web/packages/picante/vignettes/picante-intro.pdf)

```{r old school phylogenetic signal, message=FALSE, warning=FALSE}

# Ensuring trait matrix order matches the phylogenetic tree order 
trait_matrix <- trait_matrix[phy_coll3$tip.label,]

# Creating a data object that matches the tree and the traits (only including T50 and GP)
MatchDataObj= match.phylo.data(phy_coll3, trait_matrix[,c(1,3)])

# Calculating phylogenetic signal as well as P-value based on variance of phylogenetically independent contrasts relative to tip shuffling randomization.
physig = multiPhylosignal(MatchDataObj$data, MatchDataObj$phy,reps=100000)

physig


# Testing if the "scenario matters" (Scenario 2 is different than 1 or 3)
# Ensuring trait matrix order matches the phylogenetic tree order 
trait_matrix <- trait_matrix[phy_coll2$tip.label,]

# Creating a data object that matches the tree and the traits (only including T50 and GP)
MatchDataObj= match.phylo.data(phy_coll2, trait_matrix[,c(1,3)])

# Calculating phylogenetic signal as well as P-value based on variance of phylogenetically independent contrasts relative to tip shuffling randomization.
physig2 = multiPhylosignal(MatchDataObj$data, MatchDataObj$phy,reps=100000)

physig2

```

## Phylogenetic Signal MCMCglmm models

```{r phylogenetic signal models}

```
